### ISSUE TITLE
freeswitch-1.6.8: You must install libilbc-dev to build mod_ilbc

### ISSUE THREAD

**Issue by l29ah** [alphallc/freeswitch#15]
making all mod_ilbc
    make[4]: Entering directory `/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/mod/codecs/mod_ilbc'
    make[4]: Leaving directory `/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/mod/codecs/mod_ilbc'
    cd /var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/libs/tiff-4.0.2 && make
    Makefile:897: *** You must install libilbc-dev to build mod_ilbc.  Stop.
    make[3]: *** [mod_ilbc-all] Error 1

**Comment by seifertm** [comment]
Thanks for the report!

Should work as of c6e3495ef08ecb84889627c148f9cca11fe5e753. The problem was that
1. The dependency on `media-libs/libilbc` was missing
2. `configure.ac` did not find the `pkg-config` file properly

**Comment by seifertm** [comment]
Upstream issue to include the patch for `configure.ac`:
https://freeswitch.org/jira/browse/FS-9239

**Comment by seifertm** [comment]
Just fixing the configuration does not fix the issue. There is a number different implementations of ilbc, which all go by the same name (more or less). It seems like FreeSWITCH is only compatible with its own bundled version.

**Comment by seifertm** [comment]
Alright, FreeSWITCH 1.6.8. compiles on my system with mod_ilbc enabled.

Feel free to reopen the bug or open a new one, in case you experience further issues.
