### ISSUE TITLE
freeswitch-1.6.8: mod_ilbc.c:39:2: error: unknown type name 'ilbc_encode_state_t'

### ISSUE THREAD

**Issue by l29ah** [alphallc/freeswitch#16]
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../../../src/include -I../../../../libs/esl/src/include -I../../../../libs/xmlrpc-c -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/include -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/include -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/libs/libteletone/src -fPIC -I/usr/include/uuid -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/include -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/src/include -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/libs/libteletone/src -fPIC -DENABLE_ZRTP -DHAVE_OPENSSL -Wdeclaration-after-statement -I/var/tmp/paludis/net-voip-freeswitch-1.6.8/work/freeswitch-1.6.8/libs/esl/src/include -O2 -pipe -O2 -pipe -march=native -Wno-extended-offsetof -c ../../../../libs/esl/src/esl_json.c  -fPIC -DPIC -o ../../../../libs/esl/src/.libs/mod_hash_la-esl_json.o
    mod_ilbc.c:39:2: error: unknown type name 'ilbc_encode_state_t'
            ilbc_encode_state_t encoder_object;
            ^
    mod_ilbc.c:40:2: error: unknown type name 'ilbc_decode_state_t'
            ilbc_decode_state_t decoder_object;
            ^
    mod_ilbc.c:78:3: warning: implicit declaration of function 'ilbc_encode_init' is invalid in C99
          [-Wimplicit-function-declaration]
                    ilbc_encode_init(&context->encoder_object, mode);
                    ^
    mod_ilbc.c:82:3: warning: implicit declaration of function 'ilbc_decode_init' is invalid in C99
          [-Wimplicit-function-declaration]
                    ilbc_decode_init(&context->decoder_object, mode, 0);
                    ^
    mod_ilbc.c:108:22: warning: implicit declaration of function 'ilbc_encode' is invalid in C99
          [-Wimplicit-function-declaration]
            *encoded_data_len = ilbc_encode(&context->encoder_object, (uint8_t *) encoded_data, (int16_t *) de...
                                ^
    mod_ilbc.c:126:27: warning: implicit declaration of function 'ilbc_decode' is invalid in C99
          [-Wimplicit-function-declaration]
            *decoded_data_len = (2 * ilbc_decode(&context->decoder_object, (int16_t *) decoded_data, (uint8_t ...
                                     ^
    mod_ilbc.c:151:12: error: use of undeclared identifier 'ILBC_BLOCK_LEN_20MS'
                                                                                     ILBC_BLOCK_LEN_20MS * 2...
                                                                                     ^
    mod_ilbc.c:150:12: error: use of undeclared identifier 'ILBC_BLOCK_LEN_20MS'
                                                                                     ILBC_BLOCK_LEN_20MS,   /...
                                                                                     ^
    mod_ilbc.c:152:12: error: use of undeclared identifier 'ILBC_NO_OF_BYTES_20MS'
                                                                                     ILBC_NO_OF_BYTES_20MS, /...
                                                                                     ^
    mod_ilbc.c:169:12: error: use of undeclared identifier 'ILBC_BLOCK_LEN_30MS'
                                                                                     ILBC_BLOCK_LEN_30MS * 2...
                                                                                     ^
    mod_ilbc.c:168:12: error: use of undeclared identifier 'ILBC_BLOCK_LEN_30MS'
                                                                                     ILBC_BLOCK_LEN_30MS,   /...
                                                                                     ^
    mod_ilbc.c:170:12: error: use of undeclared identifier 'ILBC_NO_OF_BYTES_30MS'
                                                                                     ILBC_NO_OF_BYTES_30MS, /...
                                                                                     ^
    4 warnings and 8 errors generated.
    make[4]: *** [mod_ilbc_la-mod_ilbc.lo] Error 1

**Comment by seifertm** [comment]
Related to improper fix of #15.
