### ISSUE TITLE
fix the manifest for net-voip/freeswitch 

### ISSUE THREAD

**Issue by 257** [alphallc/freeswitch#17]
trying to emerge freeswitch i get:
> !!! Fetched file: freeswitch-1.6.8.tar.xz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      33454900
> !!! Expected: 33460304

**Comment by seifertm** [comment]
Thanks for the report. For some reason, upstream has changed the tar ball for 1.6.8. The change seems to only affect the binary archive, not the contents of the archive. Therefore I updated the Manifest to reflect the upstream changes.
The issue should be fixed.
