### ISSUE TITLE
Freeswitch service crashes without --background

### ISSUE THREAD

**Issue by joe9** [alphallc/freeswitch#20]
Hello,

The freeswitch service crashes without the --background option to start-stop-daemon.

The below command works fine.
```
     start-stop-daemon --background --user ${freeswitch_user} --group ${freeswitch_group} --start /usr/bin/freeswitch -- ${FREESWITCH_OPTS:--ncwait}
```

Thanks

**Comment by seifertm** [comment]
Thanks, added `--background` to the arguments in the init script.
