### ISSUE TITLE
Bug in all versions of freeswitch...

### ISSUE THREAD

**Issue by noci2012** [alphallc/freeswitch#25]
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I./src/include -I./libs/esl/src/include -I./libs/xmlrpc-c -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libvpx -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/src/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/src/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libteletone/src -fPIC -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DHAVE_VISIBILITY=1 -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/sofia-sip/libsofia-sip-ua/sdp -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/sofia-sip/libsofia-sip-ua/su -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/sofia-sip/libsofia-sip-ua/su -g -Wall -pthread -D_REENTRANT -D_GNU_SOURCE -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/apr/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/apr-util/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/apr-util/xml/expat/lib -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libtpl-1.5/src -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/srtp/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libyuv/include -DSWITCH_HAVE_YUV -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/srtp/crypto/include -Ilibs/srtp/crypto/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/spandsp/src -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/spandsp/src -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/tiff-4.0.2/libtiff -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/tiff-4.0.2/libtiff -DSWITCH_HAVE_VPX -DENABLE_SRTP -DSWITCH_HAVE_ODBC -I/usr/include -DSWITCH_HAVE_PNG -I/usr/include/libpng16 -DSWITCH_HAVE_FREETYPE -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libzrtp/third_party/bgaes -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libzrtp/third_party/bnlib -isystem /var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libzrtp/include -I/usr/include/freetype2 -I/usr/kerberos/include -I/usr/include/editline -I/usr/kerberos/include -DHAVE_OPENSSL -I/usr/include/uuid -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/src/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/src/include -I/var/tmp/portage/net-voip/freeswitch-1.6.19-r1/work/freeswitch-1.6.19/libs/libteletone/src -fPIC -Werror -Wno-unused-result -Wno-misleading-indentation -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DHAVE_VISIBILITY=1 -DENABLE_ZRTP -DHAVE_OPENSSL -Wdeclaration-after-statement -march=native -O2 -pipe -c src/switch_sdp.c  -fPIC -DPIC -o .libs/libfreeswitch_la-switch_sdp.o
src/switch_core_video.c: In function ‘switch_img_alloc’:
src/switch_core_video.c:205:2: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  switch_assert(r->d_h = d_h);
  ^~~~~~~~~~~~~

This has been sent to freeswitch and the bug has been be fixed in master.
Jira item: https://freeswitch.org/jira/browse/FS-11168

Can the overlay be updated?
Oh btw, also the freeswith-ilbc-0.0.1 sources have differing sizes from the downloads, so the Manifest needs verification or update.

**Comment by seifertm** [comment]
Thanks for the reports!
I will not get a chance to look at the issue before tomorrow, though.
Sorry for the delay!

**Comment by noci2012** [comment]
Freeswitch has been removed from Gentoo.  Anyway started using FusionPBX in a VM.
