### ISSUE TITLE
USE flag 'freetdm' is not in IUSE

### ISSUE THREAD

**Issue by stefantalpalaru** [alphallc/freeswitch#3]
I get the following error:

- net-voip/freeswitch-9999::freeswitch (masked by: invalid: REQUIRED_USE: USE flag 'freetdm' is not in IUSE)

Adding the flag to IUSE fixes the problem.

**Comment by seifertm** [comment]
It's not really recent anymore, but anyway :)

The freeswitch overlay provides a USE_EXPAND category for the freeswitch modules. To compile `mod_freetdm`, add

    FREESWITCH_MODULES="freetdm"

to `/etc/portage/make.conf`.
