### ISSUE TITLE
freeswitch does not depend on libpri

### ISSUE THREAD

**Issue by mikemol** [alphallc/freeswitch#4]
In configure stage for media-sound/freeswitch-9999:

<<>> Digium libpri
checking whether libpri is usable... no
configure: error: libpri not found or unusable (see config.log for details)
configure: error: ./configure.gnu failed for libs/freetdm

Followed up with eix to see if libpri was around:

$ eix libpri
* net-libs/libpri
     Available versions:  1.4.12-r1 1.4.12-r2 ~1.4.13 ~1.4.14 {{static-libs}}
     Homepage:            http://www.asterisk.org/
     Description:         Primary Rate ISDN (PRI) library

Conclusion: freeswitch ebuild does not express the needed dependency on net-libs/libpri

**Comment by seifertm** [comment]
I doubt this is still a recent issue, but anyway :)

Freeswitch currently bundles freetdm and libpri. The current ebuild (net-voip/freeswitch-1.4.18) will also install PRI support as soon as you add

    FREESWITCH_MODULES="freetdm"

to `/etc/portage/make.conf`.
