### ISSUE TITLE
  * In file '/var/paludis/repositories/freeswitch/profiles/package.mask': Error reading file: 'Error reading from fd 3: Is a directory' (paludis::SafeIFStreamError) (paludis::ConfigFileError)

### ISSUE THREAD

**Issue by l29ah** [alphallc/freeswitch#6]
profiles/package.mask must be a file according to the PMS.

**Comment by seifertm** [comment]
Thanks for the hint. I adopted the structure from kde overlay, but it should indeed be a file, not a directory.

Fixed as of 66791b2a41b09316e98dd4a4a5cb8b53cd4a674c.
