### ISSUE TITLE
net-voip/yate-9999:0::freeswitch: can't compile

### ISSUE THREAD

**Issue by l29ah** [alphallc/freeswitch#7]
x86_64-pc-linux-gnu-g++ -Wall -Wl,-O1 -Wl,--as-needed -o ../libyate.so.5.5.1 -shared -Wl,-soname=libyate.so.5.5.1 TelEngine.o ObjList.o HashList.o Mutex.o Thre
ad.o Socket.o Resolver.o String.o DataBlock.o NamedList.o URI.o Mime.o Array.o Iterator.o XML.o Hasher.o YMD5.o YSHA1.o YSHA256.o Base64.o Cipher.o Compressor.o Math.o Configuration.o Message.o Engine.o Plugin.o DataFormat.o Channel.o Client.o ClientLogic.o -lpthread -ldl   -lresolv
x86_64-pc-linux-gnu-g++ -Wall -Wl,-O1 -Wl,--as-needed -o ../libyate.so.5.5.1 -shared -Wl,-soname=libyate.so.5.5.1 TelEngine.o ObjList.o HashList.o Mutex.o Thread.o Socket.o Resolver.o String.o DataBlock.o NamedList.o URI.o Mime.o Array.o Iterator.o XML.o Hasher.o YMD5.o YSHA1.o YSHA256.o Base64.o Cipher.o Compressor.o Math.o Configuration.o Message.o Engine.o Plugin.o DataFormat.o Channel.o Client.o ClientLogic.o -lpthread -ldl   -lresolv
make[1]: Leaving directory `/var/tmp/paludis/net-voip-yate-9999/work/yate/engine'
ln -sf libyate.so.5.5.1 libyate.so
x86_64-pc-linux-gnu-g++ -Wall -Wl,-O1 -Wl,--as-needed -o yate -lpthread main.o libyate.so 
libyate.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make: *** [yate] Error 1

**Comment by seifertm** [comment]
Thanks for letting us know. ``net-voip/yate`` seems to belong to the group of ebuilds I didn't get around to clean up, yet. It is a leftover from a few years ago.

``net-voip/yate`` is available in different versions in the Portage tree. Since the are not ebuilds in the overlay that depend on yate, I removed the package completely.
